FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código y modelo
COPY web/api.py .
COPY models/model.pkl .

EXPOSE 5000

CMD ["python", "api.py"]
