apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: api-pod-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s